import Head from 'next/head';
import { useState } from 'react';

import { ScheduleData } from '@/apiHandlers/schedule/interface';
import Table from '@/components/common/CardProgram/Card';
import CardPromo from '@/components/common/CardPromo/Card';
import { NextPageWithLayout } from '@/types';

import AdsBanner from '../Dashboard/components/AdsBanner';
import Course from '../Dashboard/components/Course';
import Tabs from './components/Tabs';

const Schedule: NextPageWithLayout = () => {
  const BookIcon = 'assets/Icons/book.svg';
  const [scheduleData, setScheduleData] = useState<ScheduleData | undefined>(
    undefined,
  );

  console.log('schedule data from scene', scheduleData);
  // Example data for the table
  const tableData = [
    {
      waktu: '08:00 - 09:00',
      program: 'Cara Terbaik menjadi Dokter Spesialis Bedah',
      durasi: '60 menit',
      instruktur: 'John Doe',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
    {
      waktu: '10:00 - 11-00',
      durasi: '60 menit',
      program: 'Teknik bedah',
      instruktur: 'Jane Smith',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
    {
      waktu: '12:00 - 13:00',
      durasi: '60 menit',
      program: 'Spesialis Jantung',
      instruktur: 'Mike Johnson',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
  ];

  return (
    <>
      <Head>
        <title>Jadwal Program</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full gap-4">
        {/* <AdsBanner />
        <CardPromo />
        <Course title="Related Programs" isPrivate={false} isRelated={true} /> */}
        <Tabs setScheduleData={setScheduleData} />
        <div className="flex bg-white rounded-xl drop-shadow-lg  gap-4  flex-col  h-auto  sm:flex-row  mt-8">
          <Table data={scheduleData} />
        </div>
      </div>
    </>
  );
};

export default Schedule;
