import Head from 'next/head';
import { useState } from 'react';

import { ScheduleData } from '@/apiHandlers/schedule/interface';
import Table from '@/components/common/CardProgram/Card';
import CardPromo from '@/components/common/CardPromo/Card';
import { NextPageWithLayout } from '@/types';

const Exam: NextPageWithLayout = () => {
  const BookIcon = 'assets/Icons/book.svg';

  // Example data for the table
  const tableData = [
    {
      time: '08:00 - 09:00',
      program: 'Cara Terbaik menjadi Dokter Spesialis Bedah',
      duration: 'Senin, 10 Juni 2023',
      lecturer: 'John Doe',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
    {
      time: '10:00 - 11-00',
      duration: 'Senin, 10 Juni 2023',
      program: 'Teknik bedah',
      lecturer: 'Jane Smith',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
    {
      time: '12:00 - 13:00',
      duration: 'Senin, 10 Juni 2023',
      program: 'Spesialis Jantung',
      lecturer: 'Mike Johnson',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
    {
      time: '12:00 - 13:00',
      duration: 'Senin, 10 Juni 2023',
      program: 'Spesialis Jantung',
      lecturer: 'Mike Johnson',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
    {
      time: '12:00 - 13:00',
      duration: 'Senin, 10 Juni 2023',
      program: 'Spesialis Jantung',
      lecturer: 'Mike Johnson',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
    {
      time: '12:00 - 13:00',
      duration: 'Senin, 10 Juni 2023',
      program: 'Spesialis Jantung',
      lecturer: 'Mike Johnson',
      badges: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      icon: '/assets/Icons/Profile.svg',
      aksi: 'Edit',
    },
  ];

  return (
    <>
      <Head>
        <title>Ujian Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full gap-4">
        <p className="text-[#2C3131] text-xl font-semibold text-start sm:text-start">
          Ujian Online
        </p>
        <div className="flex bg-white rounded-xl drop-shadow-lg  gap-4  flex-col  h-auto  sm:flex-row  mt-8">
          <Table data={tableData} isExam={true} />
        </div>
      </div>
    </>
  );
};

export default Exam;
