/* eslint-disable react/no-children-prop */
import Head from 'next/head';

// import BookIcon from '@/assets/icons/book.svg';
import Card from '@/components/common/Card';
import CardPrivateOnline from '@/components/common/Homepage/CardPrivateOnline';
import { HomepageFooter } from '@/components/layouts/HompageFooter';
import { NextPageWithLayout } from '@/types';

import Table from './components/Table';

const Invoice: NextPageWithLayout = () => {
  const dummyData = [
    {
      id: 1,
      total: 'Rp1,500,000',
      status: 'Selesai',
      program: 'Cara Terbaik menjadi Dokter Spesialis Bedah',
      instrukturTenggat: 'John Doe',
      desc: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      tenggat: '10 Juni 2023',
      paidDate: '10 Juni 2023',
      idTransaction: 'E-12092309',
      action: '',
    },
    {
      id: 2,
      total: 'Rp1,500,000',
      status: 'Selesai',
      program: 'Cara Terbaik menjadi Dokter Spesialis Bedah',
      instrukturTenggat: 'Jane Smith',
      desc: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      tenggat: '10 Juni 2023',
      paidDate: '9 Juni 2023',
      idTransaction: 'E-11092309',
      action: '',
    },
    {
      id: 3,
      total: 'Rp1,500,000',
      status: 'Belum Bayar',
      program: 'Cara Terbaik menjadi Dokter Spesialis Bedah',
      instrukturTenggat: 'Bob Johnson',
      desc: 'Dokter Spesialis Gizi RSUD Sanglah Denpasar',
      tenggat: '10 Juni 2023',
      paidDate: '11 Juni 2023',
      idTransaction: 'E-13092309',
      action: '',
    },
    // {
    //   id: 4,
    //   total: 'Rp1,500,000',
    //   status: 'Active',
    //   program: 'Program D',
    //   instrukturTenggat: 'Alice Williams',
    //   tenggat: '10 Juni 2023',
    // },
    // {
    //   id: 5,
    //   total: 'Rp1,500,000',
    //   status: 'Inactive',
    //   program: 'Program E',
    //   instrukturTenggat: 'Mike Brown',
    //   tenggat: '10 Juni 2023',
    // },
  ];

  return (
    <>
      <Head>
        <title>Daftar Tagihan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <p className="text-[#2C3131] text-xl font-semibold text-start sm:text-start">
          Daftar Tagihan
        </p>
        <div className="mt-5 bg-transparent">
          <Table data={dummyData} />
        </div>
      </div>
    </>
  );
};

export default Invoice;
