import { ScheduleData, ScheduleResponse } from './interface';

export const mockScheduleData: ScheduleData[] = [
  {
    time: '09:00 - 10:30',
    program: 'Introduction to Medical Terminology',
    duration: '1.5 hours',
    lecturer: 'John Smith',
    badges: 'Dr. Specialist in Cardiology',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '10:00 - 12:00',
    program: 'Anatomy and Physiology',
    duration: '2 hours',
    lecturer: 'Jane Doe',
    badges: 'Dr. Specialist in Neurology',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '13:30 - 15:00',
    program: 'Medical Ethics and Professionalism',
    duration: '1.5 hours',
    lecturer: 'Alex Johnson',
    badges: 'Dr. Specialist in Ethics',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '14:00 - 16:00',
    program: 'Pharmacology and Medication Administration',
    duration: '2 hours',
    lecturer: 'Sarah Thompson',
    badges: 'Dr. Specialist in Pharmacology',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '16:00 - 17:30',
    program: 'Diagnostic Techniques and Medical Imaging',
    duration: '1.5 hours',
    lecturer: 'Michael Brown',
    badges: 'Dr. Specialist in Radiology',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '18:00 - 19:00',
    program: 'Medical Microbiology and Infectious Diseases',
    duration: '1 hour',
    lecturer: 'Emily Wilson',
    badges: 'Dr. Specialist in Microbiology',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '20:00 - 22:30',
    program: 'Medical Research and Evidence-Based Medicine',
    duration: '2.5 hours',
    lecturer: 'Robert Johnson',
    badges: 'Dr. Specialist in Research',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '19:30 - 20:30',
    program: 'Medical Surgical Nursing',
    duration: '1 hour',
    lecturer: 'Laura Anderson',
    badges: 'Dr. Specialist in Surgical Nursing',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '21:00 - 23:00',
    program: 'Pediatrics and Child Health',
    duration: '2 hours',
    lecturer: 'David Wilson',
    badges: 'Dr. Specialist in Pediatrics',
    icon: '/assets/Icons/Profile.svg',
  },
  {
    time: '16:30 - 18:00',
    program: 'Emergency Medicine and First Aid',
    duration: '1.5 hours',
    lecturer: 'Olivia Davis',
    badges: 'Dr. Specialist in Emergency Medicine',
    icon: '/assets/Icons/Profile.svg',
  },
];
