/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head';

import AuthBtnSubmit from '@/components/common/AuthButtonSubmit/AuthBtnSubmit';
import { AuthHeader } from '@/components/layouts/AuthHeader/AuthHeader';
import { NextPageWithLayout } from '@/types';

import ForgotPasswordForm from './container/ForgotPasswordForm';

const ForgotPassword: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthHeader
        title={'Lupa Kata Sandi'}
        desc={'Masukan email anda untuk mengubah kata sandi anda'}
      >
        <div className="flex flex-col min-h-screen">
          {/* <ForgotPasswordForm
        titleEmail={'Email'}
        titlePassword={'Password'}
        placeholderEmail={'Masukan kata email anda'}
        placeholderPassword={'Password'}
        required={false}
      /> */}

          <ForgotPasswordForm
            placeholderEmail="Masukan email anda disini"
            required={false}
            titleEmail="Email"
          />

          <div className="flex-grow-[0.9]">
            {/* Content of the component that takes space on top */}
          </div>

          {/* <div className="flex flex-col w-[100%] min-h-full justify-end">
            <label className="flex w-[100%] h-[100%] justify-center">
              Belum memiliki akun?{' '}
              <span className="text-[#E8DC00]">
                <a href="/">&nbsp;Daftar</a>
              </span>
            </label>
          </div> */}
        </div>
      </AuthHeader>
    </>
  );
};

export default ForgotPassword;
