/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head';
import { useState } from 'react';

import RegisterForm from '@/components/common/RegisterForm/RegisterForm';
import { AuthHeader } from '@/components/layouts/AuthHeader/AuthHeader';
import { NextPageWithLayout } from '@/types';

import Modal from './container/modal/Modal';

const Register: NextPageWithLayout = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const handleOpenModal = () => {
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
  };
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4 flex flex-col max-w-[488px] w-full mx-auto my-auto justify-center items-center drop-shadow-xl bg-white gap-4 rounded-xl">
        <RegisterForm onModalOpen={handleOpenModal} />
        {/* </AuthHeader> */}
        <div className="flex-grow-[0.7]">
          {/* Content of the component that takes space on top */}
        </div>
        <div className="flex flex-col w-[100%] min-h-full justify-end">
          <label className="flex w-[100%] h-[100%] justify-center ">
            Belum memiliki akun?{' '}
            <span className="text-[#E8DC00]">
              <a href="/auth/register">&nbsp;Daftar</a>
            </span>
          </label>
        </div>
      </div>
      <Modal isOpen={isModalOpen} onClose={handleCloseModal} />
    </>
  );
};

Register.disableLayout = true;

export default Register;
