/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head';
import { ToastContainer } from 'react-toastify';

import AuthBtnSubmit from '@/components/common/AuthButtonSubmit/AuthBtnSubmit';
import EmailForm from '@/components/common/LoginForm/EmailForm/EmailForm';
import LoginForm from '@/components/common/LoginForm/LoginForm';
import PasswordForm from '@/components/common/LoginForm/PasswordForm';
import { AuthHeader } from '@/components/layouts/AuthHeader/AuthHeader';
import { NextPageWithLayout, NextPageWithoutLayout } from '@/types';

const Login: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4 flex flex-col max-w-[424px] w-full mx-auto my-auto justify-center items-center drop-shadow-2xl bg-white gap-4 rounded-xl">
        {/* <AuthHeader title={'Masuk'} desc={'Silahkan masuk ke akun anda.'} /> */}
        <LoginForm
          titleEmail={'Email'}
          titlePassword={'Password'}
          placeholderEmail={'Masukan alamat email'}
          required={false}
          placeholderPassword={'Masukan kata sandi anda'}
        />

        <div className="flex w-[100%] justify-between items-center mt-[30px] flex-row mb-[20px]">
          <hr className="w-[50%] border-[1px]" />
          <label className="text-[14px] font-medium text-center text-[#9E9FA2] w-[250%] sm:w-[100%]">
            Atau masuk dengan
          </label>
          <hr className="w-[50%] border-[1px]" />
        </div>
        <div className="flex flex-col w-[100%] min-h-full justify-end">
          <div className="flex flex-row justify-between w-[100%] gap-[16px]">
            <button className="flex flex-row justify-center items-center gap-[16px] mx-[auto] border-[1px] text-[14px] border-[#F3F3F3] rounded-[12px] w-[100%] py-[10px]">
              <img
                src="/assets/GoogleIcon.png"
                alt="/"
                width={20}
                height={20}
              />{' '}
              Google
            </button>
            <button className="flex flex-row justify-center items-center gap-[16px] mx-[auto] border-[1px] text-[14px] border-[#F3F3F3] rounded-[12px] w-[100%] py-[10px]">
              <img
                src="/assets/FacebookIcon.png"
                alt="/"
                width={20}
                height={20}
              />{' '}
              Facebook
            </button>
          </div>
        </div>
        <div className="flex-grow-[0.7]">
          {/* Content of the component that takes space on top */}
        </div>
        {/* <div className="flex flex-col w-[100%] min-h-full justify-end">
          <label className="flex w-[100%] h-[100%] justify-center ">
            Belum memiliki akun?{' '}
            <span className="text-[#E8DC00]">
              <a href="/auth/register">&nbsp;Daftar</a>
            </span>
          </label>
        </div> */}
      </div>
      <ToastContainer />
    </>
  );
};

Login.disableLayout = true;

export default Login;
