/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BatchPrecompileInterface } from "./BatchPrecompileInterface";
export * as factories from "./factories";
export { BatchPrecompileInterface__factory } from "./factories/BatchPrecompileInterface__factory";
