import { Formik } from 'formik';
import Head from 'next/head';
import React, { useState } from 'react';
import { ToastContainer } from 'react-toastify';

import AuthBtnSubmit from '@/components/common/AuthButtonSubmit/AuthBtnSubmit';
import RegisterForm from '@/components/common/RegisterForm/RegisterForm';
import VerificationChoices from '@/components/common/VerificationChoice/VerificationChoices';
import { AuthHeader } from '@/components/layouts/AuthHeader/AuthHeader';
import { NextPageWithLayout } from '@/types';

import AuthOTPContent from './container/AuthOTPContent';
import Modal from './container/modal/Modal';

const Register: NextPageWithLayout = () => {
  const [submit, setSubmit] = React.useState();
  const [isModalOpen, setIsModalOpen] = useState(false);

  const handleOpenModal = () => {
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
  };
  return (
    <>
      <Head>
        <title>Metode Verifikasi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-4 flex flex-col max-w-[424px] w-full mx-auto my-auto justify-center items-center drop-shadow-xl bg-white gap-4 rounded-xl">
        <AuthOTPContent onModalOpen={handleOpenModal} />

        {/* </AuthHeader> */}
      </div>
      <Modal isOpen={isModalOpen} onClose={handleCloseModal} />
      <ToastContainer />
    </>
  );
};
Register.disableLayout = true;
export default Register;
